name: Deploy Dockerized React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t my-react-app .

    - name: Tag Docker image
      run: |
        docker tag my-react-app:latest 897729121889.dkr.ecr.ap-southeast-2.amazonaws.com/my-react-app:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push 897729121889.dkr.ecr.ap-southeast-2.amazonaws.com/my-react-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Install ECS CLI
      run: |
        curl -o ecs-cli https://d1uj6qtbmh3dt5.cloudfront.net/ecs-cli-linux-amd64-latest
        chmod +x ecs-cli
        sudo mv ecs-cli /usr/local/bin/ecs-cli

    - name: Configure ECS CLI
      run: |
        ecs-cli configure profile --access-key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --region ap-southeast-2
        ecs-cli configure --cluster my-cluster --region ap-southeast-2 --default-launch-type EC2 --config-name my-cluster
        ecs-cli compose --file docker-compose.yml service up --create-log-groups --cluster my-cluster
