name: Deploy Dockerized React App to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Log in to AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Authenticate Docker to ECR
        run: |
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com

      - name: Build Docker image
        run: docker build -t my-react-app .

      - name: Tag Docker image
        run: docker tag my-react-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/my-react-app:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/my-react-app:latest

      - name: Update ECS Task Definition
        run: |
          # Register new task definition
          aws ecs register-task-definition \
            --family my-react-app-task \
            --container-definitions '[{
              "name": "my-react-app",
              "image": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/my-react-app:latest",
              "essential": true,
              "memory": 512,
              "cpu": 256,
              "portMappings": [{
                "containerPort": 80,
                "hostPort": 80
              }]
            }]'

      - name: Deploy to ECS
        run: |
          # Update ECS service with explicit region
          aws ecs update-service \
            --cluster demo-cluster-react \
            --service my-service \
            --task-definition my-react-app-task \
            --force-new-deployment \
            --region ap-southeast-2