name: Deploy to AWS ECR and EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t my-react-app .
      
      - name: Tag Docker image
        run: |
          docker tag my-react-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-react-app:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-react-app:latest

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Install AWS CLI
          sudo apt-get install -y awscli
          
          # Connect to EC2 instance
          ssh -i "C:\Users\henze\OneDrive\Documents\DevOps\AWS\EC2 Tutorial.pem" ec2-user@13.211.75.251 << EOF
          
          # Install Docker on EC2 instance
          sudo yum update -y
          sudo amazon-linux-extras install docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          
          # Log in to ECR from EC2
          $(aws ecr get-login --no-include-email --region $AWS_REGION)
          
          # Pull Docker image from ECR
          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-react-app:latest
          
          # Stop and remove existing container if it exists
          docker ps -q -f name=my-react-app | xargs docker stop || true
          docker ps -a -q -f name=my-react-app | xargs docker rm || true
          
          # Run Docker container
          docker run -d -p 80:80 --name my-react-app ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-react-app:latest
          
          EOF
